# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NWNiZjI4ZTcxZTg3MDFhYmNjMzVlZjE2MTk4MzNkMmQ5NjdhY2M1YTg2OGNmMDdmYzYwY2IyOTIwY2IwOGNmMDYyMzRiODQyZDVkYmE5YzI5YmQyMTc1ODQ1ZGU1Zjc1MjdiMzk0MDVhZmY4ZGY3YTE2MDEzM2IzM2E4YTE0MDA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
